// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9CYdl4aTaMgfFPRpsDldARxzL6dsSX8',
    appId: '1:67595950425:web:7348814f3597e5dbc9d448',
    messagingSenderId: '67595950425',
    projectId: 'mwslaty-authentication',
    authDomain: 'mwslaty-authentication.firebaseapp.com',
    databaseURL: 'https://mwslaty-authentication-default-rtdb.firebaseio.com',
    storageBucket: 'mwslaty-authentication.firebasestorage.app',
    measurementId: 'G-FY0PHL8DSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADaSSGadoV27husO97U5lNF9LmgDmn5BU',
    appId: '1:67595950425:android:ca960685f9ca473ec9d448',
    messagingSenderId: '67595950425',
    projectId: 'mwslaty-authentication',
    databaseURL: 'https://mwslaty-authentication-default-rtdb.firebaseio.com',
    storageBucket: 'mwslaty-authentication.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsGsxtn5atni_2oXRwF5u0QPz9CRdco8',
    appId: '1:67595950425:ios:cc2dfb5c2837bae9c9d448',
    messagingSenderId: '67595950425',
    projectId: 'mwslaty-authentication',
    databaseURL: 'https://mwslaty-authentication-default-rtdb.firebaseio.com',
    storageBucket: 'mwslaty-authentication.firebasestorage.app',
    iosClientId: '67595950425-cpqklgrcui9t3q8v6p5plfpad9hjsb1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.egypttest',
  );
}
